import colors from './colors';
import baseTheme from './baseTheme';

const themeAntd = {
  components: {
    Button: {
      controlHeight: baseTheme.baseControlHeight,
      controlHeightSM: 32,
      colorLink: colors.primary.red,
      colorLinkHover: colors.additional.hover,
      colorLinkActive: colors.primary.red,
      colorPrimary: colors.primary.red,
      colorPrimaryBorder: colors.primary.black,
      colorPrimaryActive: colors.primary.red,
      colorPrimaryHover: colors.additional.hover,
      colorTextDisabled: colors.neutrals['500'],
      colorText: colors.primary.black,
      colorTextLightSolid: colors.primary.white,
      colorError: colors.primary.black,
      colorBorder: colors.primary.black,
    },
    Checkbox: {
      colorBorder: colors.neutrals['400'],
      colorPrimaryBorder: colors.primary.red,
      colorBgContainerDisabled: colors.neutrals['200'],
      colorText: colors.primary.black,
      colorTextDisabled: colors.neutrals['500'],
    },
    Input: {
      controlHeight: baseTheme.baseControlHeight,
      colorTextPlaceholder: colors.neutrals['500'],
      colorText: colors.primary.black,
      lineHeight: 1.5,
      colorBorder: colors.neutrals['400'],
      colorBgContainerDisabled: colors.neutrals['200'],
      colorErrorBorderHover: colors.secondaryWarm.red,
      colorErrorBorder: colors.secondaryWarm.red,
      colorError: colors.secondaryWarm.red,
      colorFillAlter: colors.neutrals[100],
      colorPrimaryHover: colors.neutrals[500],
      colorPrimaryActive: colors.neutrals[500],
      controlOutline: colors.additional.outline,
    },
    DatePicker: {
      colorPrimary: colors.neutrals[500],
      colorPrimaryHover: colors.neutrals[500],
      colorPrimaryActive: colors.neutrals[500],
      controlOutline: colors.additional.outline,
    },
    Select: {
      controlHeight: baseTheme.baseControlHeight,
      colorTextPlaceholder: colors.neutrals['500'],
      colorTextQuaternary: colors.neutrals['500'],
      colorTextDisabled: colors.neutrals['500'],
      controlItemBgActive: colors.neutrals['200'],
      controlItemBgHover: colors.neutrals['100'],
      fontWeightStrong: 400,
      paddingSM: 12,
      colorText: colors.primary.black,
      colorPrimaryHover: colors.neutrals[500],
      colorPrimaryActive: colors.neutrals[500],
      controlOutline: colors.additional.outline,
    },
    InputNumber: {
      controlWidth: 90,
      controlHeight: baseTheme.baseControlHeight,
      colorTextPlaceholder: colors.neutrals['500'],
      colorText: colors.primary.black,
      lineHeight: 1.5,
      colorBorder: colors.neutrals['400'],
      colorBgContainerDisabled: colors.neutrals['200'],
      colorErrorBorderHover: '#ffa39e',
      colorError: colors.secondaryWarm.red,
    },
    Switch: {
      controlHeight: 16,
      lineHeight: 1.5,
      colorTextQuaternary: colors.neutrals['400'],
    },
    Tag: {
      colorInfo: colors.navy['400'],
      colorInfoBg: colors.navy['50'],
      colorInfoBorder: colors.navy['100'],
      colorError: colors.raspberryRed['400'],
      colorErrorBg: colors.raspberryRed['50'],
      colorErrorBorder: colors.raspberryRed['100'],
      colorSuccessBorder: colors.green['100'],
      colorSuccessBg: colors.green['50'],
      colorSuccess: colors.green['400'],
      colorWarningBorder: colors.brightYellow['100'],
      colorWarningBg: colors.brightYellow['50'],
      colorWarning: colors.brightYellow['400'],
      colorTextLightSolid: colors.primary.white,

      red1: colors.raspberryRed[50],
      red3: colors.raspberryRed[100],
      red7: colors.raspberryRed[400],

      volcano1: colors.red[50],
      volcano3: colors.red[100],
      volcano7: colors.red[400],

      magenta1: colors.pink[50],
      magenta3: colors.pink[100],
      magenta7: colors.pink[400],

      yellow1: colors.brightYellow[50],
      yellow3: colors.brightYellow[100],
      yellow7: colors.brightYellow[400],

      purple1: colors.purple[50],
      purple3: colors.purple[100],
      purple7: colors.purple[400],

      lime1: colors.green[50],
      lime3: colors.green[100],
      lime7: colors.green[400],

      green1: colors.darkGreen[50],
      green3: colors.darkGreen[100],
      green7: colors.darkGreen[400],

      blue1: colors.navy[50],
      blue3: colors.navy[100],
      blue7: colors.navy[400],
    },
    Avatar: {
      colorTextPlaceholder: colors.additional.pastel,
      colorTextLightSolid: colors.primary.red,
      fontSize: 12,
    },
    Notification: {
      paddingMD: 13,
      paddingContentHorizontalLG: 15,
      fontSizeLG: 14,
      colorIcon: colors.primary.black,
      boxShadow: 'none',
    },
    Modal: {
      fontWeightStrong: 500,
      boxShadow: 'none',
      borderRadiusLG: 8,
      colorBgMask: 'rgba(0, 0, 0, 0.2)',
    },
    Alert: {
      colorError: colors.raspberryRed[400],
      colorErrorBorder: colors.raspberryRed[400],
      colorErrorBg: colors.raspberryRed[50],
      colorWarning: colors.brightYellow[400],
      colorWarningBorder: colors.brightYellow[400],
      colorWarningBg: colors.brightYellow[50],
      colorSuccess: colors.green[400],
      colorSuccessBorder: colors.green[400],
      colorSuccessBg: colors.green[50],
      colorInfo: colors.navy[400],
      colorInfoBorder: colors.navy[400],
      colorInfoBg: colors.navy[50],
      paddingContentVerticalSM: 12,
      borderRadiusLG: 8,
    },
    Badge: {
      colorError: colors.primary.red,
    },
    Table: {
      colorBgContainer: colors.neutrals[200],
      colorBorderSecondary: 'transparent',
    },
    Pagination: {
      colorBgContainer: colors.primary.red,
      colorPrimaryBorder: colors.neutrals[400],
      colorPrimary: '#fff',
      colorText: colors.neutrals[400],
      colorPrimaryHover: colors.primary.white,
      controlHeight: 32,
    },
    Menu: {
      itemColor: colors.primary.black,
      itemDisabledColor: colors.neutrals[500],
      itemBg: colors.primary.white,
      itemHoverBg: 'transparent',
      itemSelectedBg: 'transparent',
      itemSelectedColor: colors.primary.red,
      subMenuItemBg: colors.neutrals[100],
      itemHoverColor: colors.primary.red,
    },
  },
  token: {
    colorPrimary: colors.primary.red,
    colorPrimaryHover: colors.additional.hover,
    colorPrimaryActive: colors.primary.red,
    borderRadius: 4,
    fontSize: 14,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontFamily: "'Poppins', 'Inter', 'system-ui', 'Avenir', 'Helvetica', 'Arial', 'sans-serif'",
    colorErrorBorder: colors.secondaryWarm.red,
    colorErrorHover: colors.secondaryWarm.red,
    colorError: colors.secondaryWarm.red,
    colorSplit: colors.neutrals[400],
    controlHeight: 40,
    colorBgSpotlight: colors.primary.white,
    colorTextLightSolid: colors.additional.tooltipText,
    zIndexPopupBase: 1000,
  },
};

export default themeAntd;